### PR TITLE
Project migration to SBT to support cross build (Scala 2.11 and 2.12)

### PR DESCRIPTION
**Pull request by redsk**
Hi @HeartSaVioR , 

thanks for your project. Since `spark-state-tools` only supports Scala 2.11 and many developers are already using Scala 2.12, I've created this PR to support cross building it against Spark's supported Scala versions. 

As this seems to be overly complex with Maven, I've migrated the project to SBT. I believe I'm supporting the same plugins you were using before. 

Compilation, test, test with coverage, publishing (the `+` signs means the action is for both versions of Scala):
```
sbt +compile
sbt +test
sbt +coverage +test
sbt +package
sbt +publishSigned
```
Everything seems to be working (including `circleci`) but of course I couldn't check the publishing.
Please let me know what you think!

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Thanks for the great efforts! 

I'm not familiar with sbt, so if I understand correctly, sbt will execute the command with all cross versions when `+` sign is added to the command, right? If then passing circleci looks to be enough to verify the PR, except publishing as you said.

I'll play out with publishing artifact and leave comments. Thanks again!

**Comment by redsk** [comment]
> Thanks for the great efforts!

You're more than welcome!

> I'm not familiar with sbt, so if I understand correctly, sbt will execute the command with all cross versions when `+` sign is added to the command, right? 

Exactly. I've also left the default scala version to `2.11.12` which is the one you use so if you omit the `+` you shouldn't notice much difference with the previous version.

**Comment by HeartSaVioR** [comment]
I played with the change and with small changes I can publish artifacts with cross-compilation of Scala versions. Awesome!

https://github.com/HeartSaVioR/spark-state-tools/commit/43edb340c52731a98f62c3b56e0eae3833d162dc

Looks like we can't use val as it is oddly not reflected to some config. Maybe it's a matter of order or namespace or so, but allowing some duplications makes our life easier so why not?

Could you please incorporate the change in this PR? No need to preserve the authorship. Thanks in advance!

**Comment by HeartSaVioR** [comment]
Btw, would you mind if I ask for help with below repository as well?
 
https://github.com/HeartSaVioR/spark-sql-kafka-offset-committer

If you don't mind I can pick your change and apply to the repository, though it is still better to have PR. Just wanted to leave proper credit on the project.

Thanks!

**Comment by redsk** [comment]
> I played with the change and with small changes I can publish artifacts with cross-compilation of Scala versions. Awesome!

Brilliant!

> [43edb34](https://github.com/HeartSaVioR/spark-state-tools/commit/43edb340c52731a98f62c3b56e0eae3833d162dc)
> 
> Looks like we can't use val as it is oddly not reflected to some config. Maybe it's a matter of order or namespace or so, but allowing some duplications makes our life easier so why not?
> 
> Could you please incorporate the change in this PR? No need to preserve the authorship. Thanks in advance!

I cherry-picked your commit and added it to this branch.

**Comment by redsk** [comment]
> Btw, would you mind if I ask for help with below repository as well?
> 
> https://github.com/HeartSaVioR/spark-sql-kafka-offset-committer
> 
> If you don't mind I can pick your change and apply to the repository, though it is still better to have PR. Just wanted to leave proper credit on the project.

Sure, no problem. A bit busy today, I'll try in the weekend.

**Comment by HeartSaVioR** [comment]
> Sure, no problem. A bit busy today, I'll try in the weekend.

Yeah please take your time. We tend to have busy stuffs in daily job and personal things. Let's lower the priority on contributing OSP. :)

**Comment by HeartSaVioR** [comment]
LGTM. Thanks for the contribution!

**Pull request merged**
